"""Generate the shadcn/ui token bridge from `tokens.json`. GENERATED — do not hand-edit output.

    python3 tools/design/shadcn/build_shadcn.py          # write
    python3 tools/design/shadcn/build_shadcn.py --check  # fail if the checked-in files drifted

Why generate rather than paste: `projects/salamander-tail` and
`projects/global-biocommunication-visualizer` both hold COPIED design values, and both had the
drift risk recorded at the time rather than fixed. A second hand-copy of the palette would be a
third. `tokens.json` stays the single source; these files are output.

WHAT THIS IS NOT: it does not install anything, add a dependency, or touch a project. It makes
shadcn/ui adoptable. See SHADCN.md for the four-step adoption.

------------------------------------------------------------------------------------------------
THE ONE THING THAT WILL BITE: `--accent` MEANS TWO DIFFERENT THINGS.

  tools/design  --accent = the brand TEAL (#0d6d6b / #5fd0c6), the same value as --ring.
  shadcn/ui     --accent = the MUTED HOVER SURFACE behind menu items and list rows.

Map them by name and every hover state in the app becomes saturated teal, which looks
deliberate and is not. So the bridge sends the brand colour to `--primary` (where shadcn puts a
brand colour) and gives `--accent` the subtle surface it expects. Measured, not assumed: with
`--primary-foreground` taken from the theme background, contrast is 5.69:1 light and 10.04:1
dark, both clearing WCAG AA.

Because both stylesheets define `--accent` at `:root` with different meanings, a document must
not load `design.css` AND this bridge. That is not a limitation in practice -- `design.css`
exists to give zero-build projects custom elements, and a React project takes shadcn components
instead. `dev_check.py` asserts this warning is still here.
------------------------------------------------------------------------------------------------
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).parent
TOKENS = json.loads((HERE.parent / "tokens.json").read_text())

#: (shadcn variable, design token key, note). The mapping IS the deliverable -- every line is a
#: decision about what shadcn means by that name, not a rename.
MAP: list[tuple[str, str, str]] = [
    ("background",            "background",       ""),
    ("foreground",            "foreground",       ""),
    ("card",                  "surface",          "shadcn's raised surface"),
    ("card-foreground",       "foreground",       ""),
    ("popover",               "surface-2",        ""),
    ("popover-foreground",    "foreground",       ""),
    ("primary",               "accent",           "THE BRAND COLOUR GOES HERE, not --accent"),
    ("primary-foreground",    "background",       "measured 5.69:1 / 10.04:1 -- AA both themes"),
    ("secondary",             "surface-2",        ""),
    ("secondary-foreground",  "foreground",       ""),
    ("muted",                 "surface-2",        ""),
    ("muted-foreground",      "muted-foreground", ""),
    ("accent",                "surface-2",        "shadcn's hover surface -- NOT the brand teal"),
    ("accent-foreground",     "foreground",       ""),
    ("border",                "border",           ""),
    ("input",                 "border",           ""),
    ("ring",                  "ring",             ""),
]

LIGHT, DARK = "instrument", "instrument-dark"
BANNER = ("/* GENERATED by tools/design/shadcn/build_shadcn.py from tokens.json.\n"
          "   Do not hand-edit: run the generator. `--check` fails on drift.\n"
          "   NOTE: --accent here is shadcn's MUTED HOVER SURFACE. The brand colour is\n"
          "   --primary. Do not load design.css and this file in the same document. */\n")


def theme(name: str) -> dict:
    t = dict(TOKENS["color"][name])
    t.pop("note", None)
    return t


def destructive(dark: bool) -> str:
    return TOKENS["epistemic"]["families"]["refuted"]["dark" if dark else "light"]


def series(dark: bool) -> list[str]:
    s = TOKENS.get("series", {})
    key = "dark" if dark else "light"
    if isinstance(s, dict):
        for v in (s.get(key), s.get("order"), s.get("hues")):
            if isinstance(v, list) and v:
                return [x if isinstance(x, str) else x.get(key, "#888") for x in v][:5]
        vals = [v[key] if isinstance(v, dict) and key in v else v
                for k, v in s.items() if k != "note"]
        return [v for v in vals if isinstance(v, str)][:5]
    return list(s)[:5]


def pairs(dark: bool) -> list[tuple[str, str, str]]:
    t = theme(DARK if dark else LIGHT)
    out = [(var, t[src], note) for var, src, note in MAP if src in t]
    out.append(("destructive", destructive(dark), "epistemic REFUTED -- one red, one meaning"))
    out.append(("destructive-foreground", t["background"], ""))
    for i, c in enumerate(series(dark), 1):
        out.append((f"chart-{i}", c, ""))
    return out


def hex_to_hsl(h: str) -> str:
    """Tailwind v3's shadcn convention stores bare `H S% L%` and wraps in hsl() at use."""
    h = h.lstrip("#")
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    r, g, b = (int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))
    mx, mn = max(r, g, b), min(r, g, b)
    li = (mx + mn) / 2
    if mx == mn:
        hu = s = 0.0
    else:
        d = mx - mn
        s = d / (2 - mx - mn) if li > 0.5 else d / (mx + mn)
        hu = {r: (g - b) / d + (6 if g < b else 0), g: (b - r) / d + 2, b: (r - g) / d + 4}[mx]
        hu /= 6
    return f"{hu*360:.1f} {s*100:.1f}% {li*100:.1f}%"


def css_v4() -> str:
    """Tailwind v4: plain hex in :root/.dark, surfaced to utilities via @theme inline."""
    rad = TOKENS["radius"]
    L = "\n".join(f"  --{v}: {c};" + (f"  /* {n} */" if n else "") for v, c, n in pairs(False))
    D = "\n".join(f"    --{v}: {c};" for v, c, _ in pairs(True))
    names = [v for v, _, _ in pairs(False)]
    theme_map = "\n".join(f"  --color-{v}: var(--{v});" for v in names)
    return f"""{BANNER}
:root {{
{L}
  --radius: {rad['base']};
}}

.dark {{
{D}
}}

@theme inline {{
{theme_map}
  --radius-sm: {rad['sm']};
  --radius-md: {rad['base']};
  --radius-lg: {rad['lg']};
}}
"""


def css_v3() -> str:
    """Tailwind v3: shadcn's HSL-triplet convention, consumed as hsl(var(--x))."""
    rad = TOKENS["radius"]
    L = "\n".join(f"    --{v}: {hex_to_hsl(c)};" for v, c, _ in pairs(False))
    D = "\n".join(f"    --{v}: {hex_to_hsl(c)};" for v, c, _ in pairs(True))
    return f"""{BANNER}
@layer base {{
  :root {{
{L}
    --radius: {rad['base']};
  }}
  .dark {{
{D}
  }}
}}
"""


def components_json() -> str:
    return json.dumps({
        "$schema": "https://ui.shadcn.com/schema.json",
        "style": "new-york",
        "rsc": False,
        "tsx": True,
        "tailwind": {"config": "", "css": "src/index.css",
                     "baseColor": "neutral", "cssVariables": True, "prefix": ""},
        "aliases": {"components": "@/components", "utils": "@/lib/utils",
                    "ui": "@/components/ui", "lib": "@/lib", "hooks": "@/hooks"},
        "iconLibrary": "lucide",
    }, indent=2) + "\n"


def tier_tsx() -> str:
    """The one component shadcn cannot supply. Generated so the tier LIST cannot drift from
    tokens.json -- a badge vocabulary that disagrees with the source is worse than none."""
    rows = ",\n".join(
        "  %s: { label: %s, glyph: %s, family: %s, meaning: %s }" % (
            json.dumps(t["id"]), json.dumps(t["label"]), json.dumps(t["glyph"]),
            json.dumps(t["family"]), json.dumps(t["meaning"]))
        for t in TOKENS["epistemic"]["tiers"])
    return '''/* GENERATED by tools/design/shadcn/build_shadcn.py from tokens.json — do not hand-edit.
 *
 * The one component shadcn/ui cannot supply, and the one this monorepo cannot ship a UI
 * without. `tools/design`'s rule, carried into React unchanged:
 *
 *     A LABEL MAY NEVER BE HIDDEN, AND ITS EXPLANATION MUST BE.
 *
 * So <Tier> renders colour + WORD + GLYPH, always all three. Hue is never load-bearing:
 * the badge survives colour-blindness and a greyscale screenshot, because five colours
 * cannot clear an all-pairs contrast check in any ordering. There is deliberately no
 * `compact`, `iconOnly` or `hideLabel` prop — adding one re-opens the exact failure the
 * three-channel rule closes. PREDICTED must never be able to look like MEASURED.
 */
export const TIERS = {
%s,
} as const

export type TierId = keyof typeof TIERS

export function Tier({ id, className = "" }: { id: TierId; className?: string }) {
  const t = TIERS[id]
  if (!t) throw new Error(`unknown tier ${String(id)} — add it to tokens.json, not here`)
  return (
    <span
      className={`ui-tier ui-tier--${t.family} ${className}`}
      title={t.meaning}
      aria-label={`${t.label}: ${t.meaning}`}
    >
      <span aria-hidden="true">{t.glyph}</span>
      <span>{t.label}</span>
    </span>
  )
}
''' % rows


def tier_css() -> str:
    fam = TOKENS["epistemic"]["families"]
    light = "\n".join(f"  --tier-{k}: {v['light']};" for k, v in fam.items())
    dark = "\n".join(f"    --tier-{k}: {v['dark']};" for k, v in fam.items())
    sel = "\n".join(
        f".ui-tier--{k:<10} {{ --tier-color: var(--tier-{k}); }}" for k in fam)
    return f"""/* GENERATED by tools/design/shadcn/build_shadcn.py — do not hand-edit.
 * Import alongside theme.css. Kept as plain CSS rather than Tailwind classes so the
 * three-channel rule (colour + word + glyph) lives in ONE place for both the zero-build
 * projects and the React ones. */
:root {{
{light}
}}
.dark {{
{dark}
}}
.ui-tier {{
  display: inline-flex; align-items: center; gap: .4em;
  padding: .15em .5em; border-radius: var(--radius-sm, 6px);
  font-family: var(--font-mono, ui-monospace, monospace);
  font-size: .75rem; line-height: 1.4; letter-spacing: .02em;
  white-space: nowrap;
  color: var(--tier-color);
  border: 1px solid color-mix(in srgb, var(--tier-color) 35%, transparent);
  background: color-mix(in srgb, var(--tier-color) 10%, transparent);
}}
{sel}
"""


def system_css() -> str:
    """The design-system scales design.css defines and shadcn's theme does not.

    publication.css (and anything else written against design.css's token names) needs
    them to render the same in a React document. --pub-accent carries the BRAND colour,
    because here --accent is shadcn's muted hover surface.
    """
    ty, sp, rad, mo, lay = (TOKENS[k] for k in ("type", "space", "radius", "motion", "layout"))
    fam = TOKENS["epistemic"]["families"]
    ser = TOKENS["series"]

    def colours(dark: bool, ind: str) -> str:
        t = theme(DARK if dark else LIGHT)
        mode = "dark" if dark else "light"
        rows = [("faint-foreground", t["faint-foreground"]), ("border-strong", t["border-strong"])]
        rows += [(k, v[mode]) for k, v in fam.items()]
        rows += [(f"series-{i}", c) for i, c in enumerate(ser[mode], 1)]
        return "\n".join(f"{ind}--{k}: {v};" for k, v in rows)

    scales = "\n".join(
        [f"  --font-sans: {ty['sans']};", f"  --font-mono: {ty['mono']};",
         f"  --font-serif: {ty['serif']};", f"  --font-display: {ty['display']};"]
        + [f"  --text-{k}: {v};" for k, v in ty["scale"].items()]
        + [f"  --display-{k}: {v};" for k, v in ty["display_scale"].items()]
        + [f"  --space-{k}: {v};" for k, v in sp.items()]
        + [f"  --radius-{k}: {v};" for k, v in rad.items()]
        + [f"  --motion-{k}: {mo[k]};" for k in ("fast", "base", "slow", "ease")]
        + [f"  --content-max: {lay['content-max']};", "  --pub-accent: var(--primary);"])
    return f"""/* GENERATED by tools/design/shadcn/build_shadcn.py from tokens.json — do not hand-edit.
 * The design-system scales that design.css defines and the shadcn theme does not, so
 * publication.css renders identically in a React document. Import after theme.css. */
:root {{
{scales}
{colours(False, "  ")}
}}
.dark {{
{colours(True, "    ")}
}}
"""


OUTPUTS = {
    "system.css": system_css,
    "theme.css": css_v4,
    "theme.tailwind-v3.css": css_v3,
    "components.json": components_json,
    "tier.tsx": tier_tsx,
    "tier.css": tier_css,
}


def main(argv: list[str]) -> int:
    check = "--check" in argv
    bad = []
    for name, fn in OUTPUTS.items():
        want, path = fn(), HERE / name
        if check:
            if not path.is_file() or path.read_text() != want:
                bad.append(name)
        else:
            path.write_text(want)
            print(f"  wrote {path.relative_to(HERE.parent.parent.parent)}")
    if check:
        if bad:
            print(f"  DRIFT: {', '.join(bad)} differ from tokens.json — run build_shadcn.py")
            return 1
        print(f"  shadcn bridge matches tokens.json ({len(OUTPUTS)} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
