/* GENERATED by tools/design/shadcn/build_shadcn.py from tokens.json — do not hand-edit.
 *
 * The one component shadcn/ui cannot supply, and the one this monorepo cannot ship a UI
 * without. `tools/design`'s rule, carried into React unchanged:
 *
 *     A LABEL MAY NEVER BE HIDDEN, AND ITS EXPLANATION MUST BE.
 *
 * So <Tier> renders colour + WORD + GLYPH, always all three. Hue is never load-bearing:
 * the badge survives colour-blindness and a greyscale screenshot, because five colours
 * cannot clear an all-pairs contrast check in any ordering. There is deliberately no
 * `compact`, `iconOnly` or `hideLabel` prop — adding one re-opens the exact failure the
 * three-channel rule closes. PREDICTED must never be able to look like MEASURED.
 */
export const TIERS = {
  "A": { label: "[A]", glyph: "\u25c6", family: "measured", meaning: "Established, textbook-derivable, or measured here." },
  "MEASURED": { label: "MEASURED", glyph: "\u25c6", family: "measured", meaning: "Read off the actual render or a real instrument. Never styled like a prediction." },
  "PHYSICS": { label: "PHYSICS", glyph: "\u25c6", family: "measured", meaning: "Follows from physics, with the modelling choices named." },
  "B": { label: "[B]", glyph: "\u25b2", family: "predicted", meaning: "Supported by primary literature, with caveats." },
  "PREDICTED": { label: "PREDICTED", glyph: "\u25b2", family: "predicted", meaning: "Output of a model. Never styled like a measurement." },
  "MODELLED": { label: "MODELLED", glyph: "\u25b2", family: "predicted", meaning: "A chosen value that behaves plausibly; not measured." },
  "C": { label: "[C]", glyph: "\u25cf", family: "exploring", meaning: "Exploratory, weak, or contested." },
  "EXPLORATORY": { label: "EXPLORATORY", glyph: "\u25cf", family: "exploring", meaning: "An open question being actively tried. Carries a how-to-kill-it." },
  "SPEC": { label: "[SPEC]", glyph: "\u25c7", family: "spec", meaning: "Speculative. Tradition, worldbuilding, or a stated guess. Never evidence." },
  "ADDED": { label: "ADDED", glyph: "\u25c7", family: "spec", meaning: "Something the tool adds that the real thing does not do." },
  "TASTE": { label: "TASTE", glyph: "\u25c7", family: "spec", meaning: "Invented because it sounds or looks right. Not derived from anything." },
  "REFUTED": { label: "REFUTED", glyph: "\u2715", family: "refuted", meaning: "A claim this project explicitly does NOT make. Carries a scope and a cheapest probe." },
} as const

export type TierId = keyof typeof TIERS

export function Tier({ id, className = "" }: { id: TierId; className?: string }) {
  const t = TIERS[id]
  if (!t) throw new Error(`unknown tier ${String(id)} — add it to tokens.json, not here`)
  return (
    <span
      className={`ui-tier ui-tier--${t.family} ${className}`}
      title={t.meaning}
      aria-label={`${t.label}: ${t.meaning}`}
    >
      <span aria-hidden="true">{t.glyph}</span>
      <span>{t.label}</span>
    </span>
  )
}
