// Self-hosted faces. Imported from JS, not from theme.css, so the bundler resolves
// their url()s against this package rather than the consuming app.
import "./fonts.css"

export * from "./components/tier"
export * from "./components/docs"
export * from "./components/typography"
export * from "./components/value"
export * from "./charts/LineChart"
export * from "./charts/BarChart"
export * from "./charts/Waveform"
export { decimate } from "./charts/decimate"
export { SERIES, TIER_COLOR } from "./charts/common"
export * from "./publication"
export * from "./specimens"
export * from "./components/specimen"

// shadcn/ui components, restyled to the type rules (never bold, never tracked)
export * from "./components/ui/badge"
export * from "./components/ui/button"
export * from "./components/ui/card"
export * from "./components/ui/input"
export * from "./components/ui/label"
export * from "./components/ui/scroll-area"
export * from "./components/ui/select"
export * from "./components/ui/separator"
export * from "./components/ui/sheet"
export * from "./components/ui/slider"
export * from "./components/ui/table"
export * from "./components/ui/tabs"
export * from "./components/ui/tooltip"
export { cn } from "./lib/utils"
